### ISSUE TITLE
The slider pointer :after pseudo element doesn't get animation transition applied

### ISSUE THREAD

**Issue by docwhite** [angular-slider/ngx-slider#297]
If you set very slow animation durations, like 10 seconds, you will see that the small circle within the pointer hosting circle won't get transition applied.

The `.ngx-slider-pointer` gets the CSS  `transition` property applied, but not the `:after` pseudo element it creates:

Instead of:

```scss
      .ngx-slider-pointer {
        transition: all linear $animationDuration;
      }
```

I believe we should:

```scss
      .ngx-slider-pointer, .ngx-slider-pointer:after {
        transition: all linear $animationDuration;
      }
```

I will prepare a MR.
