### ISSUE TITLE
How to show tick legends but not ticks

### ISSUE THREAD

**Issue by massic80** [angular-slider/ngx-slider#344]
Similarly to #343 , I'd like to show the legends, automatically added when setting a `stepsArray` and `showTicks` or `showTicksValues` , but not the tick dots. At the moment I overrode the CSS, but I'd prefer an option to do it within the APIs.

**Comment by ms270169** [comment]
How did you override CSS?

Modification in global file `styles.css` works:
```css
.ngx-slider-tick {
    visibility: hidden!important;
}
```
But I would prefer a local solution in the component where the slider is used. Any ideas?

**Comment by massic80** [comment]
Hi, I don't remember the override (I made an amend to someone else's style customizaton), but I can see a
```css
.ngx-slider-tick {
	background-color: transparent !important;
}
```
and I figure out I implemented this solution in order to avoid "repositioning" other parts.
I'd prefer a parameter to do the same without "breaking it up"
